#cmake -DCMAKE_TOOLCHAIN_FILE=a320.cmake

SET (CMAKE_SYSTEM_NAME Linux)
SET (CMAKE_SYSTEM_VERSION 1)
SET (CMAKE_SYSTEM_PROCESSOR jz4740)

SET (DEVROOT /opt/opendingux-toolchain)
SET (_CMAKE_TOOLCHAIN_PREFIX mipsel-unknown-linux-uclibc-)
SET (_CMAKE_TOOLCHAIN_LOCATION /usr/bin)

SET (CMAKE_FIND_ROOT_PATH "${DEVROOT}")
SET (CMAKE_FIND_ROOT_PATH_MODE_PROGRAM ONLY)
SET (CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET (CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)